version: 2
jobs:
  build-test-deploy:
    docker:
      - image: circleci/python:3.6.7
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "requirements.txt" }}
      - run:
          name: Setup Environment
          command: |
            sudo apt update && sudo apt install -y openjdk-8-jre
            python3 -m venv jtp-env
            test -e && source jtp-env/bin/activate
            pip install wheel
            pip install -r ./requirements.txt

      - save_cache:
          paths:
            - ./jtp-env
          key: v1-deps-{{ checksum "requirements.txt" }}

      - run:
          name: Generate HTML
          command: |
            test -e && source jtp-env/bin/activate
            make html

      - run:
          name: Validate HTML files
          command: |
            test -e && source jtp-env/bin/activate
            make html5validate

      - run:
          name: Publish to Github pages (master branch)
          command: |
            test -e && source jtp-env/bin/activate
            make github

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-test-deploy:
          filters:
            branches:
              only: static-generator
