version: 2
jobs:
  build:
    filters:
      branches:
        only: static-generator
    docker:
      - image: circleci/python:3.6.7
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv jtp-env
            test -e && source jtp-env/bin/activate
            pip install wheel
            pip install -r ./requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-deps-{{ checksum "requirements.txt" }}

      - run:
          name: make html
          command: |
            make html

      - run:
          name: publish to github pages
          command: |
            make github

